import CoreGraphics
import Foundation

/// Turns a video or GIF into a built design, natively.
///
/// The old route ran this same code inside a booted simulator and waited for a
/// manifest to appear in its container, because the pipeline lived in the iOS
/// app. None of it is iOS-only - CoreGraphics, AVFoundation and ImageIO all
/// exist here - so the studio runs it directly and the simulator drops out of
/// the loop entirely.
///
/// The import sequence deliberately mirrors the app's, step for step: probe,
/// fit, detect the motion, let the payload planner choose quality and frame
/// rate, then retune the loop against the rate it chose. Each of those steps
/// exists because leaving it out produced a specific broken widget.
struct StudioPipeline: Sendable {
    enum Stage: Equatable, Sendable {
        case preparing
        case generating(FontSetGenerator.Stage)
        case bundling
        case installing(String)

        var caption: String {
            switch self {
            case .preparing: "Reading the clip"
            case .generating(let stage): stage.caption
            case .bundling: "Adding the fonts to the app"
            case .installing(let step): step
            }
        }

        var fraction: Double {
            switch self {
            case .preparing: 0.02
            case .generating(let stage): 0.04 + stage.fraction * 0.56
            case .bundling: 0.62
            case .installing: 0.7
            }
        }
    }

    struct Built: Sendable {
        let manifest: BuildManifest
        let folder: URL
        let summary: String
        /// Set when the design was installed but something after it was not
        /// clean - a locked phone refusing to open the app, most often.
        var warning: String?

        /// The full-screen wallpaper this design needs behind it. Offered from
        /// the Mac as well as the phone: the picture is made here, and going
        /// via Photos to fetch it back is a detour.
        var wallpaperURL: URL { folder.appendingPathComponent("wallpaper.png") }
    }

    let projectRoot: URL
    let model: DeviceModel

    /// Designs live in Application Support, not a temp directory.
    ///
    /// They were scratch until a design became worth reopening: everything
    /// placed on the canvas is in here, and a build used to be the last time
    /// anyone could see it. The OS empties a temp directory whenever it likes,
    /// which would have thrown away the layout rather than the leftovers.
    static func storeContainer() throws -> URL {
        let support = try FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        )
        return support.appendingPathComponent("Motionary", isDirectory: true)
    }

    static func openStore() throws -> DesignStore {
        try DesignStore(containerURL: try storeContainer())
    }

    private func makeStore() throws -> DesignStore {
        try Self.openStore()
    }

    /// Brings designs over from the temp store the studio used to write to.
    ///
    /// Only the design and its source clip: the fonts, preview and wallpaper
    /// are regenerated by the next build, and copying 30MB of lane fonts per
    /// design to keep a layout would be paying for the wrong thing.
    @discardableResult
    static func migrateLegacyDesigns() -> Int {
        let manager = FileManager.default
        let legacy = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("MotionaryStudio/Designs", isDirectory: true)
        guard manager.fileExists(atPath: legacy.path), let store = try? openStore() else { return 0 }

        let existing = Set(store.loadAll().map(\.id))
        var moved = 0
        let folders = (try? manager.contentsOfDirectory(at: legacy, includingPropertiesForKeys: nil)) ?? []
        for folder in folders {
            guard let id = UUID(uuidString: folder.lastPathComponent), !existing.contains(id) else { continue }
            guard let data = try? Data(contentsOf: folder.appendingPathComponent("design.json")),
                  let design = try? JSONDecoder().decode(DesignDocument.self, from: data)
            else { continue }

            let source = folder.appendingPathComponent(design.sourceVideoName)
            guard manager.fileExists(atPath: source.path) else { continue }
            do {
                try store.createFolder(for: design.id)
                let destination = store.sourceVideoURL(for: design)
                if !manager.fileExists(atPath: destination.path) {
                    try manager.copyItem(at: source, to: destination)
                }
                try store.save(design)
                moved += 1
            } catch {
                continue
            }
        }
        return moved
    }

    /// Designs already made, newest first, for reopening.
    static func saved() -> [DesignDocument] {
        guard let store = try? openStore() else { return [] }
        return store.loadAll().sorted { $0.updatedAt > $1.updatedAt }
    }

    /// Reopens a saved design in the state it was left, rather than deriving a
    /// fresh one from the clip and discarding the placement.
    func reopen(_ design: DesignDocument) async throws -> Prepared {
        let store = try makeStore()
        let poster = try? await MediaFrameExtractor(
            url: store.sourceVideoURL(for: design),
            screenSize: model.screenPixelSize
        ).posterFrame()
        return Prepared(design: design, store: store, poster: poster)
    }

    /// A design worked out from the clip, before anything is generated.
    ///
    /// Split out so there is somewhere for the editor to stand: the crop and
    /// the placement are baked into the glyphs, so they have to be settled
    /// before the fonts are built rather than adjusted afterwards.
    struct Prepared: @unchecked Sendable {
        var design: DesignDocument
        let store: DesignStore
        let poster: CGImage?
    }

    func prepare(
        source: URL,
        onStage: @escaping @Sendable (Stage) -> Void
    ) async throws -> Prepared {
        onStage(.preparing)
        let store = try makeStore()

        let data = try Data(contentsOf: source)
        // Named for what the bytes are rather than what they were called: the
        // extractor picks its decoder from the extension.
        let isGIF = data.starts(with: Data("GIF8".utf8))
        var design = DesignDocument.new(
            name: source.deletingPathExtension().lastPathComponent,
            sourceVideoName: isGIF ? "source.gif" : "source.mov"
        )
        try store.createFolder(for: design.id)
        try data.write(to: store.sourceVideoURL(for: design), options: .atomic)

        let extractor = MediaFrameExtractor(
            url: store.sourceVideoURL(for: design),
            screenSize: model.screenPixelSize
        )
        let summary = try await extractor.summary()
        design.sourceDuration = summary.duration
        design.mediaTransform = MediaTransform.suggested(
            sourceSize: summary.naturalSize,
            screenSize: model.screenPixelSize
        )

        let spec = design.spec
        let natural = max(1, Int((summary.duration * Double(spec.framesPerSecond)).rounded()))
        design.loopFrameCount = spec.seamlessLoopLength(nearest: natural, maximum: 96)
        try store.save(design)

        let poster = try? await extractor.posterFrame()
        return Prepared(design: design, store: store, poster: poster)
    }

    func generate(
        _ prepared: Prepared,
        loopSeconds: Double?,
        onStage: @escaping @Sendable (Stage) -> Void
    ) async throws -> Built {
        var design = prepared.design
        let store = prepared.store

        // Measured here rather than at import, because the editor moves and
        // resizes the clip afterwards: a crop detected against the old
        // placement would animate a region the picture has left.
        let extractor = MediaFrameExtractor(
            url: store.sourceVideoURL(for: design),
            screenSize: model.screenPixelSize,
            transform: design.mediaTransform,
            // The same background the build will use, or the motion would be
            // measured against a different picture than gets made.
            background: design.backgroundName.flatMap {
                ImageLoader.load(
                    at: store.backgroundURL(for: design.id, name: $0),
                    maxPixelSize: Int(model.screenPixelSize.height)
                )
            },
            clipRect: design.backgroundName == nil ? nil : design.widgetRect,
            clipCornerRadius: design.effectiveCornerRadius
        )
        let sample = try await extractor.composedFrames(
            startFrame: 0,
            count: min(design.loopFrameCount, 16),
            frameRate: design.spec.framesPerSecond
        )
        // The detector works across the whole screen and the motion it finds
        // can sit entirely outside the widget frame, where nothing is ever
        // drawn. A disjoint crop builds a design that cannot be built at all.
        let detection = MotionCropDetector().detect(frames: sample, screenSize: model.screenPixelSize)
        design.animationCrop = DesignDocument.usableCrop(detection.crop, in: design.widgetRect)

        // The payload ceiling decides whether the widget draws at all, so the
        // quality and frame rate come from real encoded frames rather than a
        // default that happens to be too big for this clip.
        if let plan = PayloadBudget.bestPlan(samples: sample, crop: design.effectiveCrop) {
            design.smoothness = plan.smoothness
            design.jpegQuality = plan.quality
        }
        // After the planner, never before: a loop sized against the wrong
        // frame rate plays at the wrong speed.
        design.retuneLoop()

        if let loopSeconds, loopSeconds > 0 {
            design.loopFrameCount = design.spec.seamlessLoopLength(
                nearest: max(1, Int((loopSeconds * Double(design.spec.framesPerSecond)).rounded())),
                maximum: 96
            )
        }
        try store.save(design)

        let manifest = try await FontSetGenerator(store: store).build(design: design) { stage in
            onStage(.generating(stage))
        }
        let seconds = Double(manifest.loopFrameCount) / Double(manifest.framesPerSecond)
        return Built(
            manifest: manifest,
            folder: store.folder(for: design.id),
            summary: String(
                format: "%d lanes at %dfps, %d frames (%.2fs), %.1fMB of fonts",
                manifest.laneCount,
                manifest.framesPerSecond,
                manifest.loopFrameCount,
                seconds,
                Double(manifest.totalFontBytes) / 1_048_576
            )
        )
    }

    /// The whole job: build the design, compile it into the app, install it.
    func run(
        source: URL,
        loopSeconds: Double?,
        deviceID: String?,
        onStage: @escaping @Sendable (Stage) -> Void
    ) async throws -> Built {
        let prepared = try await prepare(source: source, onStage: onStage)
        return try await install(prepared, loopSeconds: loopSeconds, deviceID: deviceID, onStage: onStage)
    }

    /// Generates and installs an already-prepared design, which is what the
    /// editor hands back.
    func install(
        _ prepared: Prepared,
        loopSeconds: Double?,
        deviceID: String?,
        onStage: @escaping @Sendable (Stage) -> Void
    ) async throws -> Built {
        let built = try await generate(prepared, loopSeconds: loopSeconds, onStage: onStage)

        onStage(.bundling)
        try BundleWriter(projectRoot: projectRoot).install(
            designFolder: built.folder,
            manifest: built.manifest,
            iconsFolder: prepared.store.root.deletingLastPathComponent()
                .appendingPathComponent("Icons", isDirectory: true)
        )
        let installer = DeviceInstaller(projectRoot: projectRoot)
        try installer.regenerateProject { onStage(.installing($0)) }

        guard let deviceID else { return built }

        var installed = built
        installed.warning = try installer.installAndLaunch(deviceID: deviceID) {
            onStage(.installing($0))
        }
        return installed
    }
}
