import Foundation

enum DesignArchiveError: Error, CustomStringConvertible {
    case noDesignInside(path: String)
    case unsupportedVersion(Int)

    var description: String {
        switch self {
        case .noDesignInside(let path):
            return "\(path) has no design.json inside it; it may not be a Motionary design"
        case .unsupportedVersion(let version):
            return "this design was written by a newer Motionary (format \(version))"
        }
    }
}

/// A design as one portable file.
///
/// Only the parts that cannot be recreated go in: the design itself, its source
/// clip, its background, and the skins its tiles use. The fonts, preview and
/// wallpaper are all regenerated by a build, and including them would turn a
/// 2MB keepsake into a 45MB one for no gain.
///
/// Skins matter especially, because they live in a library outside any design -
/// so a package without them would import as a layout with its icons missing
/// and nothing to say why.
///
/// This lived under `Mac/` while `ditto` did the packing, because `Process` is
/// not an iOS API and half of this file could not compile there. The container
/// is `ZipArchive` now, so the whole of it moves to `Shared/` rather than the
/// phone growing a second unarchiver that has to agree with this one.
struct DesignArchive {
    /// Bumped if the layout inside the package ever changes shape.
    static let formatVersion = 1

    private struct Package: Codable {
        var version: Int
        var designID: UUID
        var skins: [String]
    }

    private static func staging() throws -> URL {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("MotionaryArchive-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    // MARK: - Export

    static func export(_ design: DesignDocument, store: DesignStore, to destination: URL) throws {
        let manager = FileManager.default
        let stage = try staging()
        defer { try? manager.removeItem(at: stage) }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try encoder.encode(design).write(to: stage.appendingPathComponent("design.json"))

        let source = store.sourceVideoURL(for: design)
        if manager.fileExists(atPath: source.path) {
            try manager.copyItem(at: source, to: stage.appendingPathComponent(design.sourceVideoName))
        }
        // Variant clips are inputs like the primary one: without them the
        // import would list variants whose files stayed behind.
        for variant in design.variants {
            let clip = store.variantClipURL(for: design.id, name: variant.sourceVideoName)
            guard manager.fileExists(atPath: clip.path) else { continue }
            try manager.copyItem(at: clip, to: stage.appendingPathComponent(variant.sourceVideoName))
        }
        if let name = design.backgroundName {
            let background = store.backgroundURL(for: design.id, name: name)
            if manager.fileExists(atPath: background.path) {
                try manager.copyItem(at: background, to: stage.appendingPathComponent(name))
            }
        }

        var packaged: [String] = []
        let library = store.skinsFolder(for: design.id)
        if manager.fileExists(atPath: library.path) {
            let skinsFolder = stage.appendingPathComponent("Skins", isDirectory: true)
            try manager.createDirectory(at: skinsFolder, withIntermediateDirectories: true)
            // Alternates' skins as well as the authored tiles': a slot's
            // swapped-in occupant is drawn from the same library.
            let used = design.tiles.compactMap(\.skin)
                + design.tiles.flatMap { $0.alternates.compactMap(\.skin) }
            for name in Set(used) {
                let skin = library.appendingPathComponent(name)
                guard manager.fileExists(atPath: skin.path) else { continue }
                try manager.copyItem(at: skin, to: skinsFolder.appendingPathComponent(name))
                packaged.append(name)
            }
        }

        let package = Package(version: formatVersion, designID: design.id, skins: packaged.sorted())
        try encoder.encode(package).write(to: stage.appendingPathComponent("package.json"))

        if manager.fileExists(atPath: destination.path) {
            try manager.removeItem(at: destination)
        }
        try ZipArchive.write(directory: stage, to: destination)
    }

    // MARK: - Import

    /// Reads a package into the store, returning the design it added.
    ///
    /// A design already present is brought in as a copy under a new identity
    /// rather than overwriting it: importing a file should never be how someone
    /// loses the version they already had.
    static func restore(from archive: URL, into store: DesignStore) throws -> DesignDocument {
        let manager = FileManager.default
        let stage = try staging()
        defer { try? manager.removeItem(at: stage) }

        try ZipArchive.extract(archive, into: stage)

        guard let designURL = try locateDesign(in: stage) else {
            throw DesignArchiveError.noDesignInside(path: archive.lastPathComponent)
        }
        let folder = designURL.deletingLastPathComponent()

        if let data = try? Data(contentsOf: folder.appendingPathComponent("package.json")),
           let package = try? JSONDecoder().decode(Package.self, from: data),
           package.version > formatVersion {
            throw DesignArchiveError.unsupportedVersion(package.version)
        }

        var design = try JSONDecoder().decode(
            DesignDocument.self,
            from: try Data(contentsOf: designURL)
        )
        if manager.fileExists(atPath: store.designURL(for: design.id).path) {
            design.id = UUID()
            design.name += " copy"
        }

        try store.createFolder(for: design.id)
        let source = folder.appendingPathComponent(design.sourceVideoName)
        if manager.fileExists(atPath: source.path) {
            let destination = store.sourceVideoURL(for: design)
            if manager.fileExists(atPath: destination.path) { try manager.removeItem(at: destination) }
            try manager.copyItem(at: source, to: destination)
        }
        // Variants whose clip did not travel are dropped rather than kept as
        // rows that cannot build, the same way a missing background falls back.
        design.variants = design.variants.filter { variant in
            let packaged = folder.appendingPathComponent(variant.sourceVideoName)
            guard manager.fileExists(atPath: packaged.path) else { return false }
            let destination = store.variantClipURL(for: design.id, name: variant.sourceVideoName)
            if manager.fileExists(atPath: destination.path) { try? manager.removeItem(at: destination) }
            return (try? manager.copyItem(at: packaged, to: destination)) != nil
        }
        if let name = design.backgroundName {
            let background = folder.appendingPathComponent(name)
            if manager.fileExists(atPath: background.path) {
                let destination = store.backgroundURL(for: design.id, name: name)
                if manager.fileExists(atPath: destination.path) { try manager.removeItem(at: destination) }
                try manager.copyItem(at: background, to: destination)
            } else {
                // Said plainly by falling back rather than leaving a design
                // that points at a picture which is not there.
                design.backgroundName = nil
            }
        }

        let skinsFolder = folder.appendingPathComponent("Skins", isDirectory: true)
        let skins = (try? manager.contentsOfDirectory(at: skinsFolder, includingPropertiesForKeys: nil)) ?? []
        if !skins.isEmpty {
            let library = store.skinsFolder(for: design.id)
            try manager.createDirectory(at: library, withIntermediateDirectories: true)
            for skin in skins where skin.pathExtension == "png" {
                let destination = library.appendingPathComponent(skin.lastPathComponent)
                guard !manager.fileExists(atPath: destination.path) else { continue }
                try manager.copyItem(at: skin, to: destination)
            }
        }

        try store.save(design)
        return design
    }

    /// An archive may or may not nest its contents in a folder depending on
    /// what made it, so the design is searched for rather than assumed.
    private static func locateDesign(in root: URL) throws -> URL? {
        let manager = FileManager.default
        let direct = root.appendingPathComponent("design.json")
        if manager.fileExists(atPath: direct.path) { return direct }

        let entries = try manager.contentsOfDirectory(at: root, includingPropertiesForKeys: [.isDirectoryKey])
        for entry in entries {
            let nested = entry.appendingPathComponent("design.json")
            if manager.fileExists(atPath: nested.path) { return nested }
        }
        return nil
    }
}
